<#
.SYNOPSIS
    Generates a comprehensive security posture report for a Microsoft 365 tenant.

.DESCRIPTION
    Connects to Microsoft Graph and Exchange Online to audit the following:
    - Security Defaults status
    - Conditional Access policies
    - MFA registration status per user
    - Named Locations
    - Privileged role assignments
    - DKIM signing configuration
    - SPF and DMARC DNS records
    - Safe Links and Safe Attachments policies
    - Anti-phishing policies
    - Managed devices and compliance state
    - SSPR configuration

    Outputs a timestamped markdown report to the specified path.

.PARAMETER TenantDomain
    Primary domain of the tenant e.g. ajolnet.com

.PARAMETER OutputPath
    Folder to write the report to. Defaults to current directory.

.PARAMETER UPN
    UserPrincipalName of the account to connect with.

.EXAMPLE
    .\Get-TenantSecurityPosture.ps1 -TenantDomain "ajolnet.com" -UPN "andrew@ajolnet.com"

.EXAMPLE
    .\Get-TenantSecurityPosture.ps1 -TenantDomain "ajolnet.com" -UPN "andrew@ajolnet.com" -OutputPath "C:\Reports"

.NOTES
    Author: Andrew Jones
    Version: 1.0
    Date: 2026-03-29
    Requires: Microsoft.Graph, ExchangeOnlineManagement
    Requires: Graph scopes - Policy.Read.All, Directory.Read.All, DeviceManagementManagedDevices.Read.All,
              Reports.Read.All, AuditLog.Read.All
#>

[CmdletBinding()]
param (
    [Parameter(Mandatory)]
    [string]$TenantDomain,

    [Parameter(Mandatory)]
    [string]$UPN,

    [Parameter()]
    [string]$OutputPath = (Get-Location).Path
)

# ============================================================================
# INITIALISATION
# ============================================================================

$reportDate = Get-Date -Format "yyyy-MM-dd HH:mm"
$fileDate = Get-Date -Format "yyyy-MM-dd-HHmm"
$reportFile = Join-Path $OutputPath "Security-Posture-$fileDate.md"
$report = [System.Collections.Generic.List[string]]::new()

function Write-Section {
    param([string]$Title)
    $report.Add("")
    $report.Add("---")
    $report.Add("")
    $report.Add("## $Title")
    $report.Add("")
}

function Write-Line {
    param([string]$Line)
    $report.Add($Line)
}

function Write-Status {
    param(
        [string]$Label,
        [string]$Value,
        [ValidateSet("Good","Warning","Bad","Info")]
        [string]$Status = "Info"
    )
    $prefix = switch ($Status) {
        "Good"    { "OK" }
        "Warning" { "WARN" }
        "Bad"     { "FAIL" }
        "Info"    { "INFO" }
    }
    $report.Add("- [$prefix] $Label`: $Value")
}

function Write-TableHeader {
    param([string[]]$Headers)
    $report.Add("| " + ($Headers -join " | ") + " |")
    $report.Add("| " + (($Headers | ForEach-Object { "---" }) -join " | ") + " |")
}

function Write-TableRow {
    param([string[]]$Values)
    $report.Add("| " + ($Values -join " | ") + " |")
}

# ============================================================================
# CONNECT
# ============================================================================

# Disable WAM to prevent hidden popup issues in embedded terminals
Set-MgGraphOption -DisableLoginByWAM $true

Write-Host "Connecting to Microsoft Graph..." -ForegroundColor Cyan
Write-Host "A device code will be shown below - visit https://microsoft.com/devicelogin and enter it." -ForegroundColor Yellow
try {
    Connect-MgGraph -Scopes @(
        "Policy.Read.All",
        "Policy.ReadWrite.ConditionalAccess",
        "Directory.Read.All",
        "DeviceManagementManagedDevices.Read.All",
        "Reports.Read.All",
        "AuditLog.Read.All",
        "UserAuthenticationMethod.Read.All"
    ) -UseDeviceAuthentication -ErrorAction Stop
    Write-Host "Graph connected." -ForegroundColor Green
}
catch {
    Write-Host "Failed to connect to Microsoft Graph: $_" -ForegroundColor Red
    exit 1
}

Write-Host "Connecting to Exchange Online..." -ForegroundColor Cyan
Write-Host "A second device code will be shown below for Exchange Online." -ForegroundColor Yellow
try {
    Connect-ExchangeOnline -UserPrincipalName $UPN -ShowBanner:$false -Device -ErrorAction Stop
    Write-Host "Exchange Online connected." -ForegroundColor Green
}
catch {
    Write-Host "Failed to connect to Exchange Online: $_" -ForegroundColor Yellow
    Write-Host "MDO sections will be skipped." -ForegroundColor Yellow
    $skipExchange = $true
}

# ============================================================================
# REPORT HEADER
# ============================================================================

$report.Add("# Tenant Security Posture Report")
$report.Add("")
$report.Add("| | |")
$report.Add("|---|---|")
$report.Add("| Tenant Domain | $TenantDomain |")
$report.Add("| Report Generated | $reportDate |")
$report.Add("| Generated By | $UPN |")

# ============================================================================
# SECTION 1 - SECURITY DEFAULTS
# ============================================================================

Write-Section "Security Defaults"

try {
    $secDefaults = Get-MgPolicyIdentitySecurityDefaultEnforcementPolicy
    if ($secDefaults.IsEnabled) {
        Write-Status "Security Defaults" "Enabled - Conditional Access policies will not apply" "Bad"
        Write-Line ""
        Write-Line "Security Defaults must be disabled before Conditional Access policies can be enforced."
    }
    else {
        Write-Status "Security Defaults" "Disabled - Conditional Access is in control" "Good"
    }
}
catch {
    Write-Status "Security Defaults" "Unable to retrieve - $_" "Warning"
}

# ============================================================================
# SECTION 2 - CONDITIONAL ACCESS POLICIES
# ============================================================================

Write-Section "Conditional Access Policies"

try {
    $caPolicies = Get-MgIdentityConditionalAccessPolicy | Sort-Object DisplayName

    Write-TableHeader @("Policy Name", "State", "Include Users", "Exclude Users", "Locations", "Client Apps", "Grant")

    foreach ($policy in $caPolicies) {
        $state = switch ($policy.State) {
            "enabled" { "Enabled" }
            "disabled" { "Disabled" }
            "enabledForReportingButNotEnforced" { "Report-only" }
            default { $policy.State }
        }

        $includeUsers = ($policy.Conditions.Users.IncludeUsers + $policy.Conditions.Users.IncludeRoles) -join ", "
        if ([string]::IsNullOrEmpty($includeUsers)) { $includeUsers = "-" }

        $excludeCount = ($policy.Conditions.Users.ExcludeUsers).Count
        $excludeUsers = if ($excludeCount -gt 0) { "$excludeCount user(s) excluded" } else { "None" }

        $includeLocations = ($policy.Conditions.Locations.IncludeLocations) -join ", "
        if ([string]::IsNullOrEmpty($includeLocations)) { $includeLocations = "Not set" }

        $clientApps = ($policy.Conditions.ClientAppTypes) -join ", "
        if ([string]::IsNullOrEmpty($clientApps)) { $clientApps = "Not set" }

        $grant = ($policy.GrantControls.BuiltInControls) -join ", "
        if ([string]::IsNullOrEmpty($grant)) { $grant = "Not set" }

        Write-TableRow @($policy.DisplayName, $state, $includeUsers, $excludeUsers, $includeLocations, $clientApps, $grant)
    }

    Write-Line ""

    # Flag report-only policies
    $reportOnly = $caPolicies | Where-Object { $_.State -eq "enabledForReportingButNotEnforced" }
    if ($reportOnly) {
        foreach ($p in $reportOnly) {
            Write-Status $p.DisplayName "Report-only - not enforced" "Warning"
        }
    }

    # Flag disabled policies
    $disabled = $caPolicies | Where-Object { $_.State -eq "disabled" }
    if ($disabled) {
        foreach ($p in $disabled) {
            Write-Status $p.DisplayName "Disabled" "Bad"
        }
    }
}
catch {
    Write-Status "Conditional Access" "Unable to retrieve - $_" "Warning"
}

# ============================================================================
# SECTION 3 - NAMED LOCATIONS
# ============================================================================

Write-Section "Named Locations"

try {
    $locations = Get-MgIdentityConditionalAccessNamedLocation

    if ($locations) {
        Write-TableHeader @("Name", "Type", "ID")
        foreach ($loc in $locations) {
            $type = $loc.AdditionalProperties["@odata.type"] -replace "#microsoft.graph.", ""
            Write-TableRow @($loc.DisplayName, $type, $loc.Id)
        }
    }
    else {
        Write-Status "Named Locations" "None configured" "Warning"
    }
}
catch {
    Write-Status "Named Locations" "Unable to retrieve - $_" "Warning"
}

# ============================================================================
# SECTION 4 - MFA REGISTRATION
# ============================================================================

Write-Section "MFA Registration"

try {
    $mfaUsers = Get-MgReportAuthenticationMethodUserRegistrationDetail

    Write-TableHeader @("User", "MFA Registered", "MFA Capable", "Passwordless Capable", "Default Method")

    $mfaIssues = @()
    foreach ($user in $mfaUsers) {
        $method = if ([string]::IsNullOrEmpty($user.DefaultMfaMethod)) { "None" } else { $user.DefaultMfaMethod }
        Write-TableRow @(
            $user.UserPrincipalName,
            $user.IsMfaRegistered,
            $user.IsMfaCapable,
            $user.IsPasswordlessCapable,
            $method
        )
        if (-not $user.IsMfaRegistered) {
            $mfaIssues += $user.UserPrincipalName
        }
    }

    Write-Line ""
    if ($mfaIssues.Count -gt 0) {
        foreach ($u in $mfaIssues) {
            Write-Status "No MFA registered" $u "Warning"
        }
    }
    else {
        Write-Status "MFA Registration" "All users have MFA registered" "Good"
    }
}
catch {
    Write-Status "MFA Registration" "Unable to retrieve - $_" "Warning"
}

# ============================================================================
# SECTION 5 - PRIVILEGED ROLE ASSIGNMENTS
# ============================================================================

Write-Section "Privileged Role Assignments"

$privilegedRoles = @(
    "Global Administrator",
    "Security Administrator",
    "Exchange Administrator",
    "SharePoint Administrator",
    "Conditional Access Administrator",
    "Privileged Role Administrator",
    "User Administrator",
    "Intune Administrator",
    "Compliance Administrator",
    "Authentication Policy Administrator"
)

try {
    $allRoles = Get-MgDirectoryRole
    Write-TableHeader @("Role", "Member ID", "Count")

    $roleAssignments = @()
    foreach ($role in ($allRoles | Where-Object { $privilegedRoles -contains $_.DisplayName })) {
        $members = Get-MgDirectoryRoleMember -DirectoryRoleId $role.Id
        foreach ($member in $members) {
            $roleAssignments += [PSCustomObject]@{
                Role     = $role.DisplayName
                MemberId = $member.Id
            }
            Write-TableRow @($role.DisplayName, $member.Id, "1")
        }
    }

    Write-Line ""

    # Flag accounts with multiple high privileged roles
    $multiRole = $roleAssignments | Group-Object MemberId | Where-Object { $_.Count -gt 3 }
    foreach ($mr in $multiRole) {
        Write-Status "Multiple privileged roles" "$($mr.Name) holds $($mr.Count) privileged roles" "Warning"
    }

    # Flag GA count
    $gaCount = ($roleAssignments | Where-Object { $_.Role -eq "Global Administrator" }).Count
    if ($gaCount -gt 3) {
        Write-Status "Global Administrator count" "$gaCount accounts - consider reducing" "Warning"
    }
    elseif ($gaCount -lt 2) {
        Write-Status "Global Administrator count" "Only $gaCount account - recommend minimum 2 for break-glass" "Warning"
    }
    else {
        Write-Status "Global Administrator count" "$gaCount accounts" "Good"
    }
}
catch {
    Write-Status "Role Assignments" "Unable to retrieve - $_" "Warning"
}

# ============================================================================
# SECTION 6 - MANAGED DEVICES
# ============================================================================

Write-Section "Managed Devices"

try {
    $devices = Get-MgDeviceManagementManagedDevice

    Write-TableHeader @("Device Name", "OS", "Compliance State", "Last Sync")

    $nonCompliant = @()
    foreach ($device in $devices) {
        $lastSync = if ($device.LastSyncDateTime) { $device.LastSyncDateTime.ToString("yyyy-MM-dd HH:mm") } else { "Never" }
        Write-TableRow @($device.DeviceName, $device.OperatingSystem, $device.ComplianceState, $lastSync)
        if ($device.ComplianceState -ne "compliant") {
            $nonCompliant += $device.DeviceName
        }
    }

    Write-Line ""
    if ($nonCompliant.Count -gt 0) {
        foreach ($d in $nonCompliant) {
            Write-Status "Non-compliant device" $d "Bad"
        }
    }
    else {
        Write-Status "Device Compliance" "All $($devices.Count) devices compliant" "Good"
    }
}
catch {
    Write-Status "Managed Devices" "Unable to retrieve - $_" "Warning"
}

# ============================================================================
# SECTION 7 - SSPR
# ============================================================================

Write-Section "Self-Service Password Reset"

try {
    $sspr = Get-MgPolicyAuthenticationMethodPolicy | Select-Object -ExpandProperty RegistrationEnforcement
    $campaign = $sspr.AuthenticationMethodsRegistrationCampaign
    Write-Status "Registration Campaign State" $campaign.State "Info"
    Write-Status "Snooze Duration" "$($campaign.SnoozeDurationInDays) day(s)" "Info"
    $targets = ($campaign.IncludeTargets | ForEach-Object { $_.Id }) -join ", "
    Write-Status "Targets" $targets "Info"
}
catch {
    Write-Status "SSPR" "Unable to retrieve - $_" "Warning"
}

# ============================================================================
# SECTION 8 - DKIM
# ============================================================================

Write-Section "DKIM"

if (-not $skipExchange) {
    try {
        $dkim = Get-DkimSigningConfig | Select-Object Domain, Enabled, Status

        Write-TableHeader @("Domain", "Enabled", "Status")
        foreach ($d in $dkim) {
            Write-TableRow @($d.Domain, $d.Enabled, $d.Status)
        }

        Write-Line ""
        foreach ($d in $dkim) {
            if ($d.Enabled -and $d.Status -eq "Valid") {
                Write-Status "DKIM" "$($d.Domain) - Valid and enabled" "Good"
            }
            elseif (-not $d.Enabled) {
                Write-Status "DKIM" "$($d.Domain) - Disabled" "Bad"
            }
            else {
                Write-Status "DKIM" "$($d.Domain) - $($d.Status)" "Warning"
            }
        }
    }
    catch {
        Write-Status "DKIM" "Unable to retrieve - $_" "Warning"
    }
}
else {
    Write-Status "DKIM" "Skipped - Exchange Online not connected" "Warning"
}

# ============================================================================
# SECTION 9 - SPF AND DMARC
# ============================================================================

Write-Section "SPF and DMARC"

# SPF
try {
    $spf = Resolve-DnsName -Name $TenantDomain -Type TXT -ErrorAction Stop |
        Where-Object { $_.Strings -like "v=spf1*" } |
        Select-Object -ExpandProperty Strings

    if ($spf) {
        Write-Status "SPF Record" "Found" "Good"
        Write-Line ""
        Write-Line "```"
        Write-Line $spf
        Write-Line "```"
        Write-Line ""
        if ($spf -match "-all") {
            Write-Status "SPF Policy" "Hard fail (-all) - recommended" "Good"
        }
        elseif ($spf -match "~all") {
            Write-Status "SPF Policy" "Soft fail (~all) - consider upgrading to -all" "Warning"
        }
        elseif ($spf -match "\?all") {
            Write-Status "SPF Policy" "Neutral (?all) - not recommended" "Bad"
        }
    }
    else {
        Write-Status "SPF" "No SPF record found" "Bad"
    }
}
catch {
    Write-Status "SPF" "DNS lookup failed - $_" "Warning"
}

Write-Line ""

# DMARC
try {
    $dmarc = Resolve-DnsName -Name "_dmarc.$TenantDomain" -Type TXT -ErrorAction Stop |
        Select-Object -ExpandProperty Strings

    if ($dmarc) {
        Write-Status "DMARC Record" "Found" "Good"
        Write-Line ""
        Write-Line "```"
        Write-Line $dmarc
        Write-Line "```"
        Write-Line ""

        if ($dmarc -match "p=reject") {
            Write-Status "DMARC Policy" "Reject - recommended" "Good"
        }
        elseif ($dmarc -match "p=quarantine") {
            Write-Status "DMARC Policy" "Quarantine - consider moving to reject once stable" "Warning"
            if ($dmarc -match "pct=(\d+)") {
                $pct = $Matches[1]
                if ([int]$pct -lt 100) {
                    Write-Status "DMARC pct" "$pct% - increase to 100" "Warning"
                }
                else {
                    Write-Status "DMARC pct" "100% - correct" "Good"
                }
            }
        }
        elseif ($dmarc -match "p=none") {
            Write-Status "DMARC Policy" "None - monitoring only, not enforcing" "Bad"
        }

        if ($dmarc -match "rua=mailto:(.+?)(?:;|$)") {
            Write-Status "DMARC Reporting" "Reports sent to $($Matches[1])" "Good"
        }
        else {
            Write-Status "DMARC Reporting" "No rua address configured - reports will not be received" "Warning"
        }
    }
    else {
        Write-Status "DMARC" "No DMARC record found" "Bad"
    }
}
catch {
    Write-Status "DMARC" "DNS lookup failed - $_" "Warning"
}

# ============================================================================
# SECTION 10 - MDO SAFE LINKS AND SAFE ATTACHMENTS
# ============================================================================

Write-Section "MDO - Safe Links and Safe Attachments"

if (-not $skipExchange) {
    # Safe Links
    try {
        $safeLinks = Get-SafeLinksPolicy

        Write-Line "### Safe Links"
        Write-Line ""
        Write-TableHeader @("Policy Name", "Email", "Teams", "Office", "Scan URLs", "Track Clicks")

        foreach ($sl in $safeLinks) {
            Write-TableRow @(
                $sl.Name,
                $sl.EnableSafeLinksForEmail,
                $sl.EnableSafeLinksForTeams,
                $sl.EnableSafeLinksForOffice,
                $sl.ScanUrls,
                $sl.TrackClicks
            )
        }
    }
    catch {
        Write-Status "Safe Links" "Unable to retrieve - $_" "Warning"
    }

    Write-Line ""

    # Safe Attachments
    try {
        $safeAttach = Get-SafeAttachmentPolicy

        Write-Line "### Safe Attachments"
        Write-Line ""
        Write-TableHeader @("Policy Name", "Enabled", "Action")

        foreach ($sa in $safeAttach) {
            Write-TableRow @($sa.Name, $sa.Enable, $sa.Action)
        }
    }
    catch {
        Write-Status "Safe Attachments" "Unable to retrieve - $_" "Warning"
    }
}
else {
    Write-Status "Safe Links / Safe Attachments" "Skipped - Exchange Online not connected" "Warning"
}

# ============================================================================
# SECTION 11 - MDO ANTI-PHISHING
# ============================================================================

Write-Section "MDO - Anti-Phishing"

if (-not $skipExchange) {
    try {
        $antiPhish = Get-AntiPhishPolicy

        Write-TableHeader @("Policy", "Default", "Enabled", "Mailbox Intelligence", "Spoof Intelligence", "Impersonation Protection")

        foreach ($ap in $antiPhish) {
            Write-TableRow @(
                $ap.Name,
                $ap.IsDefault,
                $ap.Enabled,
                $ap.EnableMailboxIntelligence,
                $ap.EnableSpoofIntelligence,
                $ap.EnableImpersonationProtection
            )
        }

        Write-Line ""
        foreach ($ap in $antiPhish) {
            if ($ap.EnableImpersonationProtection -eq $false -or $null -eq $ap.EnableImpersonationProtection) {
                Write-Status "Impersonation Protection" "$($ap.Name) - not enabled" "Warning"
            }
        }
    }
    catch {
        Write-Status "Anti-Phishing" "Unable to retrieve - $_" "Warning"
    }
}
else {
    Write-Status "Anti-Phishing" "Skipped - Exchange Online not connected" "Warning"
}

# ============================================================================
# SECTION 12 - SUMMARY
# ============================================================================

Write-Section "Summary"

$goodCount = ($report | Where-Object { $_ -match "\[OK\]" }).Count
$warnCount = ($report | Where-Object { $_ -match "\[WARN\]" }).Count
$failCount = ($report | Where-Object { $_ -match "\[FAIL\]" }).Count

Write-TableHeader @("Status", "Count")
Write-TableRow @("OK", $goodCount)
Write-TableRow @("WARN", $warnCount)
Write-TableRow @("FAIL", $failCount)

Write-Line ""
Write-Line "Report saved to: $reportFile"

# ============================================================================
# WRITE REPORT
# ============================================================================

$report | Out-File -FilePath $reportFile -Encoding UTF8
Write-Host ""
Write-Host "Report complete: $reportFile" -ForegroundColor Green
Write-Host "OK: $goodCount | WARN: $warnCount | FAIL: $failCount" -ForegroundColor Cyan